version: '3'

services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=bento_cluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_DC=dc1
    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 20s
      retries: 10

  migration:
    image: cassandra:latest
    volumes:
      - ../migrations:/migrations
      - ../scripts:/scripts
    command: >
      bash -c "
        chmod +x /scripts/run_migrations.sh &&
        sleep 60 &&
        /scripts/run_migrations.sh
      "
    depends_on:
      cassandra-node1:
        condition: service_healthy